# Generated by Django 5.2.6 on 2025-11-29 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("documents", "0003_alter_document_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="AITrainingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Processing", "Processing"),
                            ("Completed", "Completed"),
                            ("Failed", "Failed"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("chunks_processed", models.IntegerField(default=0)),
                ("total_chunks", models.IntegerField(default=0)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "documents",
                    models.ManyToManyField(
                        related_name="ai_training_sessions", to="documents.document"
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Training Session",
                "verbose_name_plural": "AI Training Sessions",
                "db_table": "ai_training_sessions",
            },
        ),
        migrations.CreateModel(
            name="AIChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chunk_index", models.IntegerField(default=0)),
                ("text", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_chunks",
                        to="documents.document",
                    ),
                ),
                (
                    "training_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="ai_training.aitrainingsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Chunk",
                "verbose_name_plural": "AI Chunks",
                "db_table": "ai_chunks",
                "ordering": ["training_session", "chunk_index"],
            },
        ),
        migrations.CreateModel(
            name="TrainedModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("model_metadata", models.JSONField(blank=True, default=dict)),
                ("accuracy_score", models.FloatField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "training_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trained_models",
                        to="ai_training.aitrainingsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trained Model",
                "verbose_name_plural": "Trained Models",
                "db_table": "trained_models",
            },
        ),
    ]
