# Generated by Django 5.2.6 on 2026-04-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("parent", "Parent"),
                    ("lecturer", "Lecturer"),
                    ("admin", "Administrator"),
                ],
                default="student",
                max_length=20,
            ),
        ),
    ]
