# Generated by Django 5.2.6 on 2025-10-11 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="like",
            name="photo",
        ),
        migrations.RemoveField(
            model_name="video",
            name="occasion",
        ),
        migrations.RemoveField(
            model_name="like",
            name="video",
        ),
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[("photo", "Photo"), ("video", "Video")], max_length=10
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("caption", models.CharField(blank=True, max_length=200)),
                ("date", models.DateField()),
                ("file", models.FileField(upload_to="media/")),
                (
                    "thumbnail",
                    models.ImageField(blank=True, null=True, upload_to="thumbnails/"),
                ),
                ("likes", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "occasion",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="gallery.occasion",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="like",
            name="media",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="gallery.media",
            ),
        ),
        migrations.DeleteModel(
            name="Photo",
        ),
        migrations.DeleteModel(
            name="Video",
        ),
    ]
