# Generated by Django 5.2.6 on 2026-05-01 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0002_feedbackresponse"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedbackattachment",
            name="file_path",
        ),
        migrations.AddField(
            model_name="feedbackattachment",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="feedback_attachments/"
            ),
        ),
    ]
