# Generated by Django 5.2.6 on 2025-10-01 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={
                "ordering": ["-start_time"],
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
            },
        ),
        migrations.AddField(
            model_name="event",
            name="attendees",
            field=models.ManyToManyField(
                blank=True, related_name="event_attendees", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="cover_image",
            field=models.ImageField(blank=True, null=True, upload_to="event_covers/"),
        ),
        migrations.AddField(
            model_name="event",
            name="organizer_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="organized_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="registration_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("academic", "Academic"),
                    ("social", "Social"),
                    ("career", "Career"),
                    ("workshop", "Workshop"),
                    ("webinar", "Webinar"),
                    ("conference", "Conference"),
                    ("competition", "Competition"),
                ],
                default="academic",
                max_length=32,
            ),
        ),
    ]
