# Generated by Django 5.2.6 on 2025-10-01 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_alter_event_options_event_attendees_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="attendees",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users attending the event.",
                related_name="event_attendees",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                help_text="Optional cover image for the event.",
                null=True,
                upload_to="event_covers/",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="organizer_user",
            field=models.ForeignKey(
                blank=True,
                help_text="The actual user who organizes the event (optional).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="organized_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="registration_link",
            field=models.URLField(
                blank=True, help_text="Optional external registration link.", null=True
            ),
        ),
    ]
