# Generated by Django 5.2.6 on 2025-10-06 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="documentcategory",
            options={
                "ordering": ("display_order", "name"),
                "verbose_name": "Document Category",
                "verbose_name_plural": "Document Categories",
            },
        ),
        migrations.AddField(
            model_name="document",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="documents/"),
        ),
        migrations.AddField(
            model_name="document",
            name="status",
            field=models.CharField(
                choices=[("Draft", "Draft"), ("Published", "Published")],
                default="Draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="documents.documentcategory",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="file_path",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="document",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="documentcategory",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="documentcategory",
            name="parent_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subcategories",
                to="documents.documentcategory",
            ),
        ),
        migrations.AlterField(
            model_name="documentchunk",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
