# Generated by Django 5.2.6 on 2025-10-10 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("innovation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="innovationproject",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
    ]
