# Generated by Django 5.2.6 on 2025-09-21 23:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PathfinderQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField()),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("multiple_choice", "Multiple Choice"),
                            ("rating", "Rating"),
                            ("text", "Text"),
                        ],
                        max_length=50,
                    ),
                ),
                ("display_order", models.IntegerField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Pathfinder Question",
                "verbose_name_plural": "Pathfinder Questions",
                "db_table": "pathfinder_questions",
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField()),
                ("duration_years", models.IntegerField()),
                ("requirements", models.TextField()),
                ("career_opportunities", models.TextField(blank=True, null=True)),
                ("tuition_fee", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "additional_fees",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Program",
                "verbose_name_plural": "Programs",
                "db_table": "programs",
            },
        ),
        migrations.CreateModel(
            name="PathfinderOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("option_text", models.TextField()),
                ("option_value", models.CharField(max_length=100)),
                ("program_weights", models.JSONField(default=dict)),
                ("display_order", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="pathfinder.pathfinderquestion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pathfinder Option",
                "verbose_name_plural": "Pathfinder Options",
                "db_table": "pathfinder_options",
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="PathfinderSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completed", models.BooleanField(default=False)),
                ("results", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pathfinder_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pathfinder Session",
                "verbose_name_plural": "Pathfinder Sessions",
                "db_table": "pathfinder_sessions",
            },
        ),
        migrations.CreateModel(
            name="PathfinderAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer_value", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "option",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pathfinder.pathfinderoption",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pathfinder.pathfinderquestion",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="pathfinder.pathfindersession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pathfinder Answer",
                "verbose_name_plural": "Pathfinder Answers",
                "db_table": "pathfinder_answers",
            },
        ),
        migrations.CreateModel(
            name="ProgramFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feature_name", models.CharField(max_length=100)),
                ("feature_description", models.TextField(blank=True, null=True)),
                ("display_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="pathfinder.program",
                    ),
                ),
            ],
            options={
                "verbose_name": "Program Feature",
                "verbose_name_plural": "Program Features",
                "db_table": "program_features",
                "ordering": ["display_order"],
            },
        ),
    ]
