# Generated by Django 5.2.6 on 2025-10-17 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsetting",
            name="category",
            field=models.CharField(
                choices=[
                    ("general", "General"),
                    ("ai", "AI"),
                    ("files", "Files"),
                    ("email", "Email"),
                ],
                db_index=True,
                default="general",
                max_length=32,
            ),
        ),
    ]
