# Generated by Django 5.2.6 on 2025-11-11 15:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendar_app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="calendarevent",
            name="source",
            field=models.CharField(
                choices=[
                    ("personal", "Personal"),
                    ("events_app", "Events App"),
                    ("announcements_app", "Announcements App"),
                    ("system", "System"),
                ],
                default="personal",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="calendarevent",
            name="source_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="calendarevent",
            name="source_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="calendarevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("academic", "Academic"),
                    ("social", "Social"),
                    ("career", "Career"),
                    ("workshop", "Workshop"),
                    ("personal", "Personal"),
                    ("deadline", "Deadline"),
                    ("holiday", "Holiday"),
                    ("meeting", "Meeting"),
                    ("announcement", "Announcement"),
                    ("institutional", "Institutional"),
                ],
                default="personal",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="calendarevent",
            index=models.Index(
                fields=["source", "source_id"], name="calendar_ap_source_d87ff3_idx"
            ),
        ),
    ]
