# Generated by Django 5.2.6 on 2025-09-23 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HandbookSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        choices=[
                            ("admissions", "Admissions & Enrollment"),
                            ("academics", "Academic Programs"),
                            ("fees", "Tuition & Fees"),
                            ("policies", "Policies & Procedures"),
                            ("campus", "Campus Life"),
                            ("resources", "Student Resources"),
                        ],
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("icon", models.CharField(default="fas fa-book", max_length=64)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="HandbookContentBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=128)),
                ("body", models.TextField(help_text="Supports Markdown or HTML.")),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="handbook.handbooksection",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HandbookTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=128)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tables",
                        to="handbook.handbooksection",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HandbookTableRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("values", models.JSONField(help_text="List of cell values in order")),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="handbook.handbooktable",
                    ),
                ),
            ],
        ),
    ]
